# Generated by Django 2.0.6 on 2019-03-01 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=30)),
                ('hours', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_work', models.DateField()),
                ('date_of_entry', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
