# Generated by Django 2.0.6 on 2019-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniApp', '0002_auto_20190301_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecardmodel',
            name='date_of_work',
            field=models.CharField(max_length=200),
        ),
    ]
